/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'quantity' : bigint, 'product' : Product }
export interface ContactSubmission {
  'name' : string,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export interface Product {
  'id' : bigint,
  'collection' : string,
  'name' : string,
  'description' : string,
  'isBestseller' : boolean,
  'category' : string,
  'colors' : Array<string>,
  'priceINR' : bigint,
}
export interface _SERVICE {
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'cartClear' : ActorMethod<[], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'getAllContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getBestsellers' : ActorMethod<[], Array<Product>>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getProductById' : ActorMethod<[bigint], [] | [Product]>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getProductsByCollection' : ActorMethod<[string], Array<Product>>,
  'removeFromCart' : ActorMethod<[bigint], undefined>,
  'submitContactForm' : ActorMethod<[string, string, string, string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];